PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/3381ecb9133a5a720d54582b9b6fbebd84e7dc0f

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (17ab6178778ee8dee62882566e3abf24e6360646)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...3381ecb9133a5a720d54582b9b6fbebd84e7dc0f

3381ecb913 (HEAD, origin/master) Remove CONFIG_BUILTIN_PROXY_STACKSIZE from README files
ba331e8ea8 Run refresh.sh after CONFIG_BUILTIN_PROXY_STACKSIZE removal
b21e809d58 sim: Use generic name (cc) than GCC specific (gcc)
842392beda Makefile.host: Use generic name (cc) than GCC specific (gcc)
3a1515b473 mm_mallinfo: Fix a minfo printf-format
1a3f59be58 sim: Make hostfs build for macOS
7409f57d40 net/pkt:  Fix inconsistent use of FAR
710da6022d Fix comment typos
22d002762b sim: Add more names to nuttx-names.dat
3d425280b6 simuart: Don't assume a specific endian

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/c5673957cc270d3e8d0b9fc4293cb0be56114592

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (17ab6178778ee8dee62882566e3abf24e6360646)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...c5673957cc270d3e8d0b9fc4293cb0be56114592

c5673957 (HEAD -> master, origin/master) Remove unused BUILTIN_PROXY_STACKSIZE config
44b8c9c5 apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib